### ISSUE TITLE
Error with matplotlib latest version

### ISSUE THREAD

**Issue by alouiset** [hyperspy/hyperspy#3682]
I just reinstalled hyperspy with the latest matplotlib version (3.11.1) and I got an error when calling `s.align_zero_loss_peak()`. I downgraded my matplotlib version to 3.10.9 and the error disappeared. Looks like the issue comes from updates in matplotlib 3.11. I am on windows11 (don't know if this is relevant).

I didn't investigate further, so I don't know if something goes wrong with `Signal1D.shift1D()` as well.

Here is the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], [line 1](vscode-notebook-cell:?execution_count=12&line=1)
----> [1](vscode-notebook-cell:?execution_count=12&line=1) s_ll.align_zero_loss_peak(also_align=[s_hl])

File ~\uvenv\tem\Lib\site-packages\exspy\signals\eels.py:439, in EELSSpectrum.align_zero_loss_peak(self, calibrate, also_align, print_stats, subpixel, mask, signal_range, show_progressbar, crop, **kwargs)
    434     if zlpc._lazy:
    435         # We must compute right now because otherwise any changes to the
    436         # axes_manager of the signal later in the workflow may result in
    437         # a wrong shift_array
    438         shift_array = shift_array.compute()
--> [439](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/exspy/signals/eels.py:439)     signal.shift1D(shift_array, crop=crop, show_progressbar=show_progressbar)
    441 if calibrate is True:
    442     zlpc = estimate_zero_loss_peak_centre(
    443         self, mask=mask, signal_range=signal_range
    444     )

File ~\uvenv\tem\Lib\site-packages\hyperspy\_signals\signal1d.py:534, in Signal1D.shift1D(self, shift_array, interpolation_method, crop, expand, fill_value, show_progressbar, num_workers)
    531 if isinstance(shift_array, np.ndarray):
    532     shift_array = signals.BaseSignal(shift_array.squeeze()).T
--> [534](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/_signals/signal1d.py:534) self.map(
    535     _shift1D,
    536     shift=shift_array,
    537     original_axis=axis.axis,
    538     fill_value=fill_value,
    539     kind=interpolation_method,
    540     show_progressbar=show_progressbar,
    541     num_workers=num_workers,
    542     ragged=False,
    543 )
    545 if crop and not expand:
    546     _logger.debug("Cropping %s from index %i to %i" % (self, ilow, ihigh))

File ~\uvenv\tem\Lib\site-packages\hyperspy\signal.py:5670, in BaseSignal.map(self, function, show_progressbar, num_workers, inplace, ragged, navigation_chunks, output_signal_size, output_dtype, lazy_output, silence_warnings, **kwargs)
   5668     return result
   5669 else:
-> [5670](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/signal.py:5670)     self.events.data_changed.trigger(obj=self)

File <string>:4, in trigger(self, obj)
      2 'Could not get source, probably due dynamically evaluated source code.'

File ~\uvenv\tem\Lib\site-packages\hyperspy\events.py:427, in Event.trigger(self, **kwargs)
    425 for function, kwsl in connected_some:
    426     if function not in self._suppressed_callbacks:
--> [427](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/events.py:427)         function(**{kw: kwargs.get(kw, None) for kw in kwsl})
    428 for function, kwsd in connected_map:
    429     if function not in self._suppressed_callbacks:

File ~\uvenv\tem\Lib\site-packages\hyperspy\signal.py:3506, in BaseSignal.update_plot(self)
   3504     self._plot.signal_plot.update()
   3505 if self._plot.navigator_plot is not None:
-> [3506](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/signal.py:3506)     self._plot.navigator_plot.update()

File ~\uvenv\tem\Lib\site-packages\hyperspy\drawing\image.py:572, in ImagePlot.update(self, data_changed, auto_contrast, vmin, vmax, **kwargs)
    570         self.figure.canvas.draw_idle()  # draw without rendering not supported for sub-figures
    571     else:
--> [572](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/drawing/image.py:572)         self.figure.draw_without_rendering()
    573     self._colorbar.solids.set_animated(self.figure.canvas.supports_blit)
    574 else:

File ~\uvenv\tem\Lib\site-packages\matplotlib\figure.py:3298, in Figure.draw_without_rendering(self)
   3296 renderer = _get_renderer(self)
   3297 with renderer._draw_disabled():
-> [3298](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/figure.py:3298)     self.draw(renderer)

File ~\uvenv\tem\Lib\site-packages\matplotlib\artist.py:94, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
     92 @wraps(draw)
     93 def draw_wrapper(artist, renderer, *args, **kwargs):
---> [94](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/artist.py:94)     result = draw(artist, renderer, *args, **kwargs)
     95     if renderer._rasterizing:
     96         renderer.stop_rasterizing()

File ~\uvenv\tem\Lib\site-packages\matplotlib\artist.py:71, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     68     if artist.get_agg_filter() is not None:
     69         renderer.start_filter()
---> [71](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/artist.py:71)     return draw(artist, renderer)
     72 finally:
     73     if artist.get_agg_filter() is not None:

File ~\uvenv\tem\Lib\site-packages\matplotlib\figure.py:3289, in Figure.draw(self, renderer)
   3286 finally:
   3287     self.stale = False
-> [3289](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/figure.py:3289) DrawEvent("draw_event", self.canvas, renderer)._process()

File ~\uvenv\tem\Lib\site-packages\matplotlib\backend_bases.py:1202, in Event._process(self)
   1200 def _process(self):
   1201     """Process this event on ``self.canvas``, then unset ``guiEvent``."""
-> [1202](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/backend_bases.py:1202)     self.canvas.callbacks.process(self.name, self)
   1203     self.guiEvent = None

File ~\uvenv\tem\Lib\site-packages\matplotlib\cbook.py:395, in CallbackRegistry.process(self, s, *args, **kwargs)
    393 except Exception as exc:
    394     if self.exception_handler is not None:
--> [395](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/cbook.py:395)         self.exception_handler(exc)
    396     else:
    397         raise

File ~\uvenv\tem\Lib\site-packages\matplotlib\cbook.py:114, in _exception_printer(exc)
    112 def _exception_printer(exc):
    113     if _get_running_interactive_framework() in ["headless", None]:
--> [114](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/cbook.py:114)         raise exc
    115     else:
    116         traceback.print_exc()

File ~\uvenv\tem\Lib\site-packages\matplotlib\cbook.py:390, in CallbackRegistry.process(self, s, *args, **kwargs)
    388 if func is not None:
    389     try:
--> [390](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/matplotlib/cbook.py:390)         func(*args, **kwargs)
    391     # this does not capture KeyboardInterrupt, SystemExit,
    392     # and GeneratorExit
    393     except Exception as exc:

File ~\uvenv\tem\Lib\site-packages\hyperspy\drawing\figure.py:81, in BlittedFigure._on_blit_draw(self, *args)
     77 fig = self.figure
     78 # As draw doesn't draw animated elements, in its current state the
     79 # canvas only contains the background. The following line simply stores
     80 # it for the consumption of _update_animated.
---> [81](https://file+.vscode-resource.vscode-cdn.net/d%3A/Neel_postdoc/STEM_EELS/20260420_FDR/~/uvenv/tem/Lib/site-packages/hyperspy/drawing/figure.py:81) self._background = fig.canvas.copy_from_bbox(fig.bbox)
     82 # draw does not draw animated elements, so we must draw them
     83 # manually
     84 self._draw_animated()

AttributeError: 'FigureCanvasBase' object has no attribute 'copy_from_bbox'
"""
```

Hopefully, this is easy to fix.
Cheers!

**Comment by jat255** [comment]
@alouiset, thanks for reporting this!

I was able to reproduce this on matplotlib 3.11.1, and it works as designed on 3.10.9, like you saw. `align_zero_loss_peak` is just the entry point that shows the bug further up in HyperSpy (so transferred there from eXSpy). Anything that triggers `data_changed` on a plotted signal will hit this (`shift1D`, `map`, …).

(The following is AI assisted with Opus 5)

### Root cause

`matplotlib` 3.11 added a canvas reset when a figure manager is destroyed (`FigureManagerBase.destroy()` → `Figure._set_base_canvas()`, `backend_bases.py:2885`), which replaces `figure.canvas` with a plain `FigureCanvasBase`. Two pre-existing HyperSpy assumptions turn that into a crash:

1. `BlittedFigure.create_figure` (`hyperspy/drawing/figure.py:71`) checks `canvas.supports_blit` **once** and connects `_on_blit_draw` to `draw_event`. The callback registry lives on the *Figure* (`Figure._canvas_callbacks`, exposed through the `FigureCanvasBase.callbacks` property), so the connection survives the canvas swap while `_on_blit_draw` (line 81) still calls `fig.canvas.copy_from_bbox` unconditionally. `render_figure` (line 169) re-checks `supports_blit`; `_on_blit_draw` does not — that asymmetry is the bug.
2. Nothing tells HyperSpy the figure went away. With the inline backend (VS Code/Jupyter default), `matplotlib_inline`'s `flush_figures` calls `plt.close("all")` after every cell → `Gcf.destroy_all()` → `manager.destroy()`. `close_event` is only emitted by GUI backends, so HyperSpy's `_on_figure_window_close` never runs and `s._plot.navigator_plot` stays live pointing at a manager-less figure.

So in the next cell, the navigator's colorbar redraw path (`image.py:576`, `figure.draw_without_rendering()`) fires `draw_event` on the now-base canvas. The traceback surfaces instead of being swallowed because `cbook._exception_printer` re-raises when the running interactive framework is `None`.

### Evidence

Minimal reproduction in a uv one-liner:

```bash
# works with matplotlib 3.10
uv run --no-project --with hyperspy --with "matplotlib==3.10.9" python -c "import matplotlib; matplotlib.use('agg'); import matplotlib.pyplot as plt, numpy as np, hyperspy.api as hs; s = hs.signals.Signal1D(np.random.random((10, 10, 50))); s.plot(); plt.close('all'); s.shift1D(np.random.random((10, 10)) * 0.5)"
```

```bash
# Fails with matplotlib 3.11
uv run --no-project --with hyperspy --with "matplotlib==3.11.1" python -c "import matplotlib; matplotlib.use('agg'); import matplotlib.pyplot as plt, numpy as np, hyperspy.api as hs; s = hs.signals.Signal1D(np.random.random((10, 10, 50))); s.plot(); plt.close('all'); s.shift1D(np.random.random((10, 10)) * 0.5)"
# AttributeError: 'FigureCanvasBase' object has no attribute 'copy_from_bbox'
```

### Suggested Fix

Guarding `_on_blit_draw` on `fig.canvas.supports_blit` (reset `self._background = None` and return) fixes both repros. All 650 tests in `hyperspy/tests/drawing` pass on 3.11.1 both before and after the guard, so this looks like the only 3.11 fallout in the covered plotting paths.
